// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/farming/v1beta1/farming.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PlanType enumerates the valid types of a plan.
type PlanType int32

const (
	// PLAN_TYPE_UNSPECIFIED defines the default plan type.
	PlanTypeNil PlanType = 0
	// PLAN_TYPE_PUBLIC defines the public plan type.
	PlanTypePublic PlanType = 1
	// PLAN_TYPE_PRIVATE defines the private plan type.
	PlanTypePrivate PlanType = 2
)

var PlanType_name = map[int32]string{
	0: "PLAN_TYPE_UNSPECIFIED",
	1: "PLAN_TYPE_PUBLIC",
	2: "PLAN_TYPE_PRIVATE",
}

var PlanType_value = map[string]int32{
	"PLAN_TYPE_UNSPECIFIED": 0,
	"PLAN_TYPE_PUBLIC":      1,
	"PLAN_TYPE_PRIVATE":     2,
}

func (x PlanType) String() string {
	return proto.EnumName(PlanType_name, int32(x))
}

func (PlanType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5b657e0809d9de86, []int{0}
}

// Params defines the set of params for the farming module.
type Params struct {
	// private_plan_creation_fee specifies the fee for plan creation
	// this fee prevents from spamming and it is collected in the community pool
	PrivatePlanCreationFee github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=private_plan_creation_fee,json=privatePlanCreationFee,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"private_plan_creation_fee" yaml:"private_plan_creation_fee"`
	// next_epoch_days is the epoch length in number of days
	// it updates internal state called CurrentEpochDays that is used to process
	// staking and reward distribution in end blocker
	NextEpochDays uint32 `protobuf:"varint,2,opt,name=next_epoch_days,json=nextEpochDays,proto3" json:"next_epoch_days,omitempty" yaml:"next_epoch_days"`
	// farming_fee_collector is the module account address to collect fees within the farming module
	FarmingFeeCollector string `protobuf:"bytes,3,opt,name=farming_fee_collector,json=farmingFeeCollector,proto3" json:"farming_fee_collector,omitempty" yaml:"farming_fee_collector"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b657e0809d9de86, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// BasePlan defines a base plan type. It contains all the necessary fields
// for basic farming plan functionality. Any custom farming plan type should
// extend this type for additional functionality (e.g. fixed amount plan, ratio
// plan).
type BasePlan struct {
	// id specifies index of the farming plan
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name specifies the name for the base plan
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// type specifies the plan type; type 0 is public and 1 is private
	// public plan must be created through governance proposal and private plan is
	// created by account
	Type PlanType `protobuf:"varint,3,opt,name=type,proto3,enum=cosmos.farming.v1beta1.PlanType" json:"type,omitempty"`
	// farming_pool_address defines the bech32-encoded address of the farming pool
	FarmingPoolAddress string `protobuf:"bytes,4,opt,name=farming_pool_address,json=farmingPoolAddress,proto3" json:"farming_pool_address,omitempty" yaml:"farming_pool_address"`
	// termination_address defines the bech32-encoded address that terminates plan
	// when the plan ends after the end time, the balance of farming pool address
	// is transferred to the termination address
	TerminationAddress string `protobuf:"bytes,5,opt,name=termination_address,json=terminationAddress,proto3" json:"termination_address,omitempty" yaml:"termination_address"`
	// staking_coin_weights specifies coin weights for the plan
	StakingCoinWeights github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,6,rep,name=staking_coin_weights,json=stakingCoinWeights,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"staking_coin_weights" yaml:"staking_coin_weights"`
	// start_time specifies the start time of the plan
	StartTime time.Time `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
	// end_time specifies the end time of the plan
	EndTime time.Time `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time" yaml:"end_time"`
	// terminated indicates whether the plan has been terminated or not
	Terminated bool `protobuf:"varint,9,opt,name=terminated,proto3" json:"terminated,omitempty"`
	// last_distribution_time specifies the last time a distribution happened
	LastDistributionTime *time.Time `protobuf:"bytes,10,opt,name=last_distribution_time,json=lastDistributionTime,proto3,stdtime" json:"last_distribution_time,omitempty" yaml:"last_distribution_time"`
	// distributed_coins specifies the total coins distributed by this plan
	DistributedCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,11,rep,name=distributed_coins,json=distributedCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"distributed_coins" yaml:"distributed_coins"`
}

func (m *BasePlan) Reset()      { *m = BasePlan{} }
func (*BasePlan) ProtoMessage() {}
func (*BasePlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b657e0809d9de86, []int{1}
}
func (m *BasePlan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BasePlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BasePlan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BasePlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasePlan.Merge(m, src)
}
func (m *BasePlan) XXX_Size() int {
	return m.Size()
}
func (m *BasePlan) XXX_DiscardUnknown() {
	xxx_messageInfo_BasePlan.DiscardUnknown(m)
}

var xxx_messageInfo_BasePlan proto.InternalMessageInfo

// FixedAmountPlan defines a fixed amount plan that fixed amount of coins are
// distributed for every epoch.
type FixedAmountPlan struct {
	*BasePlan `protobuf:"bytes,1,opt,name=base_plan,json=basePlan,proto3,embedded=base_plan" json:"base_plan,omitempty" yaml:"base_plan"`
	// epoch_amount specifies the distributing amount for each epoch
	EpochAmount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=epoch_amount,json=epochAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"epoch_amount" yaml:"epoch_amount"`
}

func (m *FixedAmountPlan) Reset()      { *m = FixedAmountPlan{} }
func (*FixedAmountPlan) ProtoMessage() {}
func (*FixedAmountPlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b657e0809d9de86, []int{2}
}
func (m *FixedAmountPlan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FixedAmountPlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FixedAmountPlan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FixedAmountPlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedAmountPlan.Merge(m, src)
}
func (m *FixedAmountPlan) XXX_Size() int {
	return m.Size()
}
func (m *FixedAmountPlan) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedAmountPlan.DiscardUnknown(m)
}

var xxx_messageInfo_FixedAmountPlan proto.InternalMessageInfo

// RatioPlan defines a ratio plan that ratio of total coins in farming pool
// address is distributed for every epoch.
type RatioPlan struct {
	*BasePlan `protobuf:"bytes,1,opt,name=base_plan,json=basePlan,proto3,embedded=base_plan" json:"base_plan,omitempty" yaml:"base_plan"`
	// epoch_ratio specifies the distributing amount by ratio
	EpochRatio github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=epoch_ratio,json=epochRatio,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"epoch_ratio" yaml:"epoch_ratio"`
}

func (m *RatioPlan) Reset()      { *m = RatioPlan{} }
func (*RatioPlan) ProtoMessage() {}
func (*RatioPlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b657e0809d9de86, []int{3}
}
func (m *RatioPlan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RatioPlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RatioPlan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RatioPlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatioPlan.Merge(m, src)
}
func (m *RatioPlan) XXX_Size() int {
	return m.Size()
}
func (m *RatioPlan) XXX_DiscardUnknown() {
	xxx_messageInfo_RatioPlan.DiscardUnknown(m)
}

var xxx_messageInfo_RatioPlan proto.InternalMessageInfo

// Staking defines a farmer's staking information.
type Staking struct {
	Amount        github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
	StartingEpoch uint64                                 `protobuf:"varint,2,opt,name=starting_epoch,json=startingEpoch,proto3" json:"starting_epoch,omitempty" yaml:"starting_epoch"`
}

func (m *Staking) Reset()      { *m = Staking{} }
func (*Staking) ProtoMessage() {}
func (*Staking) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b657e0809d9de86, []int{4}
}
func (m *Staking) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Staking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Staking.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Staking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Staking.Merge(m, src)
}
func (m *Staking) XXX_Size() int {
	return m.Size()
}
func (m *Staking) XXX_DiscardUnknown() {
	xxx_messageInfo_Staking.DiscardUnknown(m)
}

var xxx_messageInfo_Staking proto.InternalMessageInfo

type QueuedStaking struct {
	Amount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
}

func (m *QueuedStaking) Reset()         { *m = QueuedStaking{} }
func (m *QueuedStaking) String() string { return proto.CompactTextString(m) }
func (*QueuedStaking) ProtoMessage()    {}
func (*QueuedStaking) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b657e0809d9de86, []int{5}
}
func (m *QueuedStaking) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueuedStaking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueuedStaking.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueuedStaking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuedStaking.Merge(m, src)
}
func (m *QueuedStaking) XXX_Size() int {
	return m.Size()
}
func (m *QueuedStaking) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuedStaking.DiscardUnknown(m)
}

var xxx_messageInfo_QueuedStaking proto.InternalMessageInfo

type TotalStakings struct {
	Amount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
}

func (m *TotalStakings) Reset()         { *m = TotalStakings{} }
func (m *TotalStakings) String() string { return proto.CompactTextString(m) }
func (*TotalStakings) ProtoMessage()    {}
func (*TotalStakings) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b657e0809d9de86, []int{6}
}
func (m *TotalStakings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TotalStakings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TotalStakings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TotalStakings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalStakings.Merge(m, src)
}
func (m *TotalStakings) XXX_Size() int {
	return m.Size()
}
func (m *TotalStakings) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalStakings.DiscardUnknown(m)
}

var xxx_messageInfo_TotalStakings proto.InternalMessageInfo

type HistoricalRewards struct {
	CumulativeUnitRewards github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,1,rep,name=cumulative_unit_rewards,json=cumulativeUnitRewards,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"cumulative_unit_rewards" yaml:"cumulative_unit_rewards"`
}

func (m *HistoricalRewards) Reset()         { *m = HistoricalRewards{} }
func (m *HistoricalRewards) String() string { return proto.CompactTextString(m) }
func (*HistoricalRewards) ProtoMessage()    {}
func (*HistoricalRewards) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b657e0809d9de86, []int{7}
}
func (m *HistoricalRewards) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HistoricalRewards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HistoricalRewards.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HistoricalRewards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoricalRewards.Merge(m, src)
}
func (m *HistoricalRewards) XXX_Size() int {
	return m.Size()
}
func (m *HistoricalRewards) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoricalRewards.DiscardUnknown(m)
}

var xxx_messageInfo_HistoricalRewards proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cosmos.farming.v1beta1.PlanType", PlanType_name, PlanType_value)
	proto.RegisterType((*Params)(nil), "cosmos.farming.v1beta1.Params")
	proto.RegisterType((*BasePlan)(nil), "cosmos.farming.v1beta1.BasePlan")
	proto.RegisterType((*FixedAmountPlan)(nil), "cosmos.farming.v1beta1.FixedAmountPlan")
	proto.RegisterType((*RatioPlan)(nil), "cosmos.farming.v1beta1.RatioPlan")
	proto.RegisterType((*Staking)(nil), "cosmos.farming.v1beta1.Staking")
	proto.RegisterType((*QueuedStaking)(nil), "cosmos.farming.v1beta1.QueuedStaking")
	proto.RegisterType((*TotalStakings)(nil), "cosmos.farming.v1beta1.TotalStakings")
	proto.RegisterType((*HistoricalRewards)(nil), "cosmos.farming.v1beta1.HistoricalRewards")
}

func init() {
	proto.RegisterFile("tendermint/farming/v1beta1/farming.proto", fileDescriptor_5b657e0809d9de86)
}

var fileDescriptor_5b657e0809d9de86 = []byte{
	// 1118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xf7, 0xb8, 0x6e, 0x62, 0x8f, 0x49, 0xe2, 0x4c, 0xfe, 0xb0, 0x71, 0x5b, 0xef, 0x6a, 0x25,
	0x90, 0x55, 0x54, 0x5b, 0x0d, 0x9c, 0x72, 0x22, 0xce, 0x9f, 0x62, 0x29, 0x0a, 0xee, 0xd6, 0xa1,
	0x80, 0x84, 0x56, 0xe3, 0xdd, 0x89, 0xb3, 0xea, 0x7a, 0xc7, 0xda, 0x19, 0xe7, 0xcf, 0x07, 0x40,
	0x8a, 0x72, 0xaa, 0x10, 0x07, 0x2e, 0x41, 0x15, 0xdc, 0xca, 0x95, 0xef, 0x40, 0x8f, 0x11, 0x12,
	0x12, 0x70, 0xd8, 0xa2, 0xe4, 0x1b, 0xf8, 0xcc, 0x01, 0xed, 0xcc, 0xac, 0xbb, 0x80, 0x43, 0x1a,
	0xa9, 0x9c, 0xbc, 0xf3, 0xe6, 0xf7, 0x7e, 0xef, 0xf7, 0xde, 0xbe, 0xf7, 0xbc, 0xb0, 0xca, 0x49,
	0xe0, 0x92, 0xb0, 0xe7, 0x05, 0xbc, 0xbe, 0x8b, 0xe3, 0xdf, 0x6e, 0x7d, 0xff, 0x7e, 0x87, 0x70,
	0x7c, 0x3f, 0x39, 0xd7, 0xfa, 0x21, 0xe5, 0x14, 0x2d, 0x3a, 0x94, 0xf5, 0x28, 0xab, 0x25, 0x56,
	0x85, 0x2a, 0xcf, 0x77, 0x69, 0x97, 0x0a, 0x48, 0x3d, 0x7e, 0x92, 0xe8, 0xf2, 0x92, 0x44, 0xdb,
	0xf2, 0x42, 0xb9, 0xca, 0xab, 0x8a, 0x3c, 0xd5, 0x3b, 0x98, 0x91, 0x51, 0x2c, 0x87, 0x7a, 0x81,
	0xba, 0xd7, 0xbb, 0x94, 0x76, 0x7d, 0x52, 0x17, 0xa7, 0xce, 0x60, 0xb7, 0xce, 0xbd, 0x1e, 0x61,
	0x1c, 0xf7, 0xfa, 0x12, 0x60, 0xfe, 0x96, 0x85, 0x13, 0x2d, 0x1c, 0xe2, 0x1e, 0x43, 0xcf, 0x01,
	0x5c, 0xea, 0x87, 0xde, 0x3e, 0xe6, 0xc4, 0xee, 0xfb, 0x38, 0xb0, 0x9d, 0x90, 0x60, 0xee, 0xd1,
	0xc0, 0xde, 0x25, 0x44, 0x03, 0xc6, 0x8d, 0x6a, 0x71, 0x79, 0xa9, 0xa6, 0xc2, 0xc7, 0x01, 0x13,
	0xd9, 0xb5, 0x35, 0xea, 0x05, 0x8d, 0xf6, 0x8b, 0x48, 0xcf, 0x0c, 0x23, 0xdd, 0x38, 0xc2, 0x3d,
	0x7f, 0xc5, 0xbc, 0x94, 0xc9, 0x7c, 0xfe, 0x52, 0xaf, 0x76, 0x3d, 0xbe, 0x37, 0xe8, 0xd4, 0x1c,
	0xda, 0x53, 0xf9, 0xa8, 0x9f, 0x7b, 0xcc, 0x7d, 0x52, 0xe7, 0x47, 0x7d, 0xc2, 0x04, 0x29, 0xb3,
	0x16, 0x15, 0x4f, 0xcb, 0xc7, 0xc1, 0x9a, 0x62, 0xd9, 0x24, 0x04, 0x35, 0xe0, 0x4c, 0x40, 0x0e,
	0xb9, 0x4d, 0xfa, 0xd4, 0xd9, 0xb3, 0x5d, 0x7c, 0xc4, 0xb4, 0xac, 0x01, 0xaa, 0x53, 0x8d, 0xf2,
	0x30, 0xd2, 0x17, 0xa5, 0x84, 0x7f, 0x00, 0x4c, 0x6b, 0x2a, 0xb6, 0x6c, 0xc4, 0x86, 0x75, 0x7c,
	0xc4, 0x50, 0x1b, 0x2e, 0xa8, 0x17, 0x10, 0xeb, 0xb2, 0x1d, 0xea, 0xfb, 0xc4, 0xe1, 0x34, 0xd4,
	0x6e, 0x18, 0xa0, 0x5a, 0x68, 0x18, 0xc3, 0x48, 0xbf, 0x2d, 0x99, 0xc6, 0xc2, 0x4c, 0x6b, 0x4e,
	0xd9, 0x37, 0x09, 0x59, 0x4b, 0xac, 0x2b, 0xf9, 0xe3, 0x67, 0x7a, 0xe6, 0x9b, 0x67, 0x7a, 0xc6,
	0xfc, 0x76, 0x12, 0xe6, 0x1b, 0x98, 0x09, 0xed, 0x68, 0x1a, 0x66, 0x3d, 0x57, 0x03, 0x06, 0xa8,
	0xe6, 0xac, 0xac, 0xe7, 0x22, 0x04, 0x73, 0x01, 0xee, 0x11, 0xa1, 0xba, 0x60, 0x89, 0x67, 0xf4,
	0x01, 0xcc, 0xc5, 0xb9, 0x8b, 0xf8, 0xd3, 0xcb, 0x46, 0x6d, 0x7c, 0x97, 0xd4, 0x62, 0xbe, 0xf6,
	0x51, 0x9f, 0x58, 0x02, 0x8d, 0x1e, 0xc2, 0xf9, 0x44, 0x5f, 0x9f, 0x52, 0xdf, 0xc6, 0xae, 0x1b,
	0x12, 0xc6, 0xb4, 0x9c, 0xc8, 0x42, 0x1f, 0x46, 0xfa, 0xad, 0xbf, 0x67, 0x91, 0x46, 0x99, 0x16,
	0x52, 0xe6, 0x16, 0xa5, 0xfe, 0xaa, 0x34, 0xa2, 0x8f, 0xe1, 0x1c, 0x17, 0x8d, 0x2c, 0xdf, 0x5a,
	0xc2, 0x78, 0x53, 0x30, 0x56, 0x86, 0x91, 0x5e, 0x96, 0x8c, 0x63, 0x40, 0xa6, 0x85, 0x52, 0xd6,
	0x84, 0xf0, 0x3b, 0x00, 0xe7, 0x19, 0xc7, 0x4f, 0xe2, 0xf0, 0x71, 0x7b, 0xda, 0x07, 0xc4, 0xeb,
	0xee, 0x71, 0xa6, 0x4d, 0x88, 0xb6, 0xba, 0x3d, 0xb6, 0xad, 0xd6, 0x89, 0x23, 0x3a, 0xcb, 0x52,
	0x9d, 0xa5, 0xd2, 0x18, 0xc7, 0x13, 0x37, 0xd5, 0x7b, 0xaf, 0xd1, 0x54, 0x8a, 0x92, 0x59, 0x48,
	0xb1, 0xc4, 0xa7, 0xc7, 0x92, 0x03, 0x7d, 0x0a, 0x21, 0xe3, 0x38, 0xe4, 0x76, 0x3c, 0x24, 0xda,
	0xa4, 0x01, 0xaa, 0xc5, 0xe5, 0x72, 0x4d, 0x4e, 0x50, 0x2d, 0x99, 0xa0, 0x5a, 0x3b, 0x99, 0xa0,
	0xc6, 0x1d, 0xa5, 0x6b, 0x76, 0xa4, 0x4b, 0xf9, 0x9a, 0x4f, 0x5f, 0xea, 0xc0, 0x2a, 0x08, 0x43,
	0x0c, 0x47, 0x16, 0xcc, 0x93, 0xc0, 0x95, 0xbc, 0xf9, 0x2b, 0x79, 0x6f, 0x29, 0xde, 0x19, 0xc9,
	0x9b, 0x78, 0x4a, 0xd6, 0x49, 0x12, 0xb8, 0x82, 0xb3, 0x02, 0x61, 0x52, 0x68, 0xe2, 0x6a, 0x05,
	0x03, 0x54, 0xf3, 0x56, 0xca, 0x82, 0x0e, 0xe0, 0xa2, 0x8f, 0x19, 0xb7, 0x5d, 0x8f, 0xf1, 0xd0,
	0xeb, 0x0c, 0xc4, 0x4b, 0x12, 0x0a, 0xe0, 0x95, 0x0a, 0xde, 0x19, 0x46, 0xfa, 0x1d, 0x19, 0x7d,
	0x3c, 0x87, 0xd4, 0x32, 0x1f, 0x5f, 0xae, 0xa7, 0xee, 0x84, 0xb0, 0xaf, 0x01, 0x9c, 0x1d, 0x39,
	0x10, 0x57, 0xbc, 0x27, 0xa6, 0x15, 0xaf, 0xda, 0x1f, 0x5b, 0x2a, 0x6b, 0x4d, 0xc6, 0xfd, 0x17,
	0xc3, 0xf5, 0xf6, 0x46, 0x29, 0xe5, 0x2f, 0x2c, 0x2b, 0xb3, 0xc9, 0x5c, 0xfe, 0xfc, 0xe3, 0xbd,
	0x9b, 0xf1, 0x08, 0x35, 0xcd, 0x3f, 0x01, 0x9c, 0xd9, 0xf4, 0x0e, 0x89, 0xbb, 0xda, 0xa3, 0x83,
	0x80, 0x8b, 0x39, 0x7d, 0x0c, 0x0b, 0xb1, 0x36, 0xb1, 0xb7, 0xc4, 0xb8, 0x16, 0x2f, 0x1f, 0xc4,
	0x64, 0xb8, 0x1b, 0xda, 0x59, 0xa4, 0x83, 0x61, 0xa4, 0x97, 0xa4, 0xf6, 0x11, 0x81, 0x69, 0xe5,
	0x3b, 0xc9, 0x02, 0xf8, 0x12, 0xc0, 0xb7, 0xe4, 0x32, 0xc2, 0x22, 0x9a, 0x96, 0xbd, 0xaa, 0x22,
	0x0f, 0x54, 0x45, 0xe6, 0x54, 0x1f, 0xa4, 0x9c, 0xaf, 0x57, 0x8c, 0xa2, 0x70, 0x95, 0x49, 0xa6,
	0xf6, 0xd3, 0x2f, 0x00, 0x16, 0xac, 0x78, 0x4c, 0xff, 0xdf, 0xc4, 0x09, 0x94, 0xf1, 0xed, 0x30,
	0x8e, 0x25, 0x17, 0x5e, 0x63, 0x3d, 0xce, 0xed, 0xf7, 0x48, 0x7f, 0xf7, 0xf5, 0x86, 0x76, 0x18,
	0xe9, 0x28, 0x5d, 0x05, 0x41, 0x65, 0x5a, 0x50, 0x9c, 0x44, 0x0e, 0xa9, 0xbc, 0x4e, 0x01, 0x9c,
	0x7c, 0x24, 0xc7, 0x1b, 0x6d, 0xc2, 0x09, 0x55, 0x6e, 0x20, 0xe2, 0xd6, 0xae, 0x11, 0xb7, 0x19,
	0x70, 0x4b, 0x79, 0xa3, 0x0f, 0xe1, 0xb4, 0x18, 0xe7, 0x78, 0xf1, 0x88, 0xa0, 0x22, 0x8f, 0x5c,
	0x63, 0x69, 0x18, 0xe9, 0x0b, 0xa9, 0xf9, 0x1f, 0xdd, 0x9b, 0xd6, 0x54, 0x62, 0x10, 0xff, 0x38,
	0x29, 0x7d, 0x5f, 0xc0, 0xa9, 0x87, 0x03, 0x32, 0x20, 0xee, 0x1b, 0x16, 0xb9, 0x92, 0x3b, 0x56,
	0xf4, 0x6d, 0xca, 0xb1, 0xaf, 0xd8, 0xd9, 0x1b, 0xa6, 0xff, 0x09, 0xc0, 0xd9, 0x8f, 0x3c, 0xc6,
	0x69, 0xe8, 0x39, 0xd8, 0xb7, 0xc8, 0x01, 0x0e, 0x5d, 0x86, 0x7e, 0x00, 0xf0, 0x6d, 0x67, 0xd0,
	0x1b, 0xf8, 0x98, 0x7b, 0xfb, 0xc4, 0x1e, 0x04, 0x1e, 0xb7, 0x43, 0x79, 0xa7, 0x3e, 0x1d, 0xfe,
	0x7b, 0xc7, 0xef, 0xa8, 0x5e, 0xaf, 0xc8, 0x5a, 0x5e, 0x42, 0x75, 0xed, 0x35, 0xbf, 0xf0, 0x8a,
	0x68, 0x27, 0xf0, 0xb8, 0x52, 0x2b, 0x33, 0xb9, 0xfb, 0x15, 0x80, 0xf9, 0xe4, 0xbf, 0x14, 0xdd,
	0x85, 0x0b, 0xad, 0xad, 0xd5, 0x6d, 0xbb, 0xfd, 0x59, 0x6b, 0xc3, 0xde, 0xd9, 0x7e, 0xd4, 0xda,
	0x58, 0x6b, 0x6e, 0x36, 0x37, 0xd6, 0x4b, 0x99, 0xf2, 0xcc, 0xc9, 0xa9, 0x51, 0x4c, 0x80, 0xdb,
	0x9e, 0x8f, 0xaa, 0xb0, 0xf4, 0x0a, 0xdb, 0xda, 0x69, 0x6c, 0x35, 0xd7, 0x4a, 0xa0, 0x8c, 0x4e,
	0x4e, 0x8d, 0xe9, 0x04, 0xd6, 0x1a, 0x74, 0x7c, 0xcf, 0x41, 0x77, 0xe1, 0x6c, 0x0a, 0x69, 0x35,
	0x3f, 0x59, 0x6d, 0x6f, 0x94, 0xb2, 0xe5, 0xb9, 0x93, 0x53, 0x63, 0x66, 0x04, 0x95, 0x5f, 0x38,
	0xe5, 0xdc, 0xf1, 0xf7, 0x95, 0x4c, 0xe3, 0xc1, 0x8b, 0xf3, 0x0a, 0x38, 0x3b, 0xaf, 0x80, 0x3f,
	0xce, 0x2b, 0xe0, 0xe9, 0x45, 0x25, 0x73, 0x76, 0x51, 0xc9, 0xfc, 0x7a, 0x51, 0xc9, 0x7c, 0x7e,
	0x2f, 0x95, 0xf8, 0x98, 0x2f, 0xcd, 0xc3, 0xd1, 0x93, 0xa8, 0x41, 0x67, 0x42, 0xec, 0xf5, 0xf7,
	0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x24, 0x4e, 0x93, 0x41, 0x96, 0x0a, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FarmingFeeCollector) > 0 {
		i -= len(m.FarmingFeeCollector)
		copy(dAtA[i:], m.FarmingFeeCollector)
		i = encodeVarintFarming(dAtA, i, uint64(len(m.FarmingFeeCollector)))
		i--
		dAtA[i] = 0x1a
	}
	if m.NextEpochDays != 0 {
		i = encodeVarintFarming(dAtA, i, uint64(m.NextEpochDays))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PrivatePlanCreationFee) > 0 {
		for iNdEx := len(m.PrivatePlanCreationFee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PrivatePlanCreationFee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFarming(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *BasePlan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BasePlan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BasePlan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DistributedCoins) > 0 {
		for iNdEx := len(m.DistributedCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DistributedCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFarming(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if m.LastDistributionTime != nil {
		n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.LastDistributionTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.LastDistributionTime):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintFarming(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x52
	}
	if m.Terminated {
		i--
		if m.Terminated {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintFarming(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x42
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintFarming(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x3a
	if len(m.StakingCoinWeights) > 0 {
		for iNdEx := len(m.StakingCoinWeights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakingCoinWeights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFarming(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.TerminationAddress) > 0 {
		i -= len(m.TerminationAddress)
		copy(dAtA[i:], m.TerminationAddress)
		i = encodeVarintFarming(dAtA, i, uint64(len(m.TerminationAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.FarmingPoolAddress) > 0 {
		i -= len(m.FarmingPoolAddress)
		copy(dAtA[i:], m.FarmingPoolAddress)
		i = encodeVarintFarming(dAtA, i, uint64(len(m.FarmingPoolAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.Type != 0 {
		i = encodeVarintFarming(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintFarming(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintFarming(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FixedAmountPlan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FixedAmountPlan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FixedAmountPlan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EpochAmount) > 0 {
		for iNdEx := len(m.EpochAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EpochAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFarming(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.BasePlan != nil {
		{
			size, err := m.BasePlan.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFarming(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RatioPlan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RatioPlan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RatioPlan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.EpochRatio.Size()
		i -= size
		if _, err := m.EpochRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFarming(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.BasePlan != nil {
		{
			size, err := m.BasePlan.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFarming(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Staking) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Staking) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Staking) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StartingEpoch != 0 {
		i = encodeVarintFarming(dAtA, i, uint64(m.StartingEpoch))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFarming(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueuedStaking) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueuedStaking) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueuedStaking) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFarming(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TotalStakings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TotalStakings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TotalStakings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFarming(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *HistoricalRewards) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HistoricalRewards) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HistoricalRewards) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CumulativeUnitRewards) > 0 {
		for iNdEx := len(m.CumulativeUnitRewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CumulativeUnitRewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFarming(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintFarming(dAtA []byte, offset int, v uint64) int {
	offset -= sovFarming(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PrivatePlanCreationFee) > 0 {
		for _, e := range m.PrivatePlanCreationFee {
			l = e.Size()
			n += 1 + l + sovFarming(uint64(l))
		}
	}
	if m.NextEpochDays != 0 {
		n += 1 + sovFarming(uint64(m.NextEpochDays))
	}
	l = len(m.FarmingFeeCollector)
	if l > 0 {
		n += 1 + l + sovFarming(uint64(l))
	}
	return n
}

func (m *BasePlan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovFarming(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovFarming(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovFarming(uint64(m.Type))
	}
	l = len(m.FarmingPoolAddress)
	if l > 0 {
		n += 1 + l + sovFarming(uint64(l))
	}
	l = len(m.TerminationAddress)
	if l > 0 {
		n += 1 + l + sovFarming(uint64(l))
	}
	if len(m.StakingCoinWeights) > 0 {
		for _, e := range m.StakingCoinWeights {
			l = e.Size()
			n += 1 + l + sovFarming(uint64(l))
		}
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovFarming(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovFarming(uint64(l))
	if m.Terminated {
		n += 2
	}
	if m.LastDistributionTime != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.LastDistributionTime)
		n += 1 + l + sovFarming(uint64(l))
	}
	if len(m.DistributedCoins) > 0 {
		for _, e := range m.DistributedCoins {
			l = e.Size()
			n += 1 + l + sovFarming(uint64(l))
		}
	}
	return n
}

func (m *FixedAmountPlan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BasePlan != nil {
		l = m.BasePlan.Size()
		n += 1 + l + sovFarming(uint64(l))
	}
	if len(m.EpochAmount) > 0 {
		for _, e := range m.EpochAmount {
			l = e.Size()
			n += 1 + l + sovFarming(uint64(l))
		}
	}
	return n
}

func (m *RatioPlan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BasePlan != nil {
		l = m.BasePlan.Size()
		n += 1 + l + sovFarming(uint64(l))
	}
	l = m.EpochRatio.Size()
	n += 1 + l + sovFarming(uint64(l))
	return n
}

func (m *Staking) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Amount.Size()
	n += 1 + l + sovFarming(uint64(l))
	if m.StartingEpoch != 0 {
		n += 1 + sovFarming(uint64(m.StartingEpoch))
	}
	return n
}

func (m *QueuedStaking) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Amount.Size()
	n += 1 + l + sovFarming(uint64(l))
	return n
}

func (m *TotalStakings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Amount.Size()
	n += 1 + l + sovFarming(uint64(l))
	return n
}

func (m *HistoricalRewards) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CumulativeUnitRewards) > 0 {
		for _, e := range m.CumulativeUnitRewards {
			l = e.Size()
			n += 1 + l + sovFarming(uint64(l))
		}
	}
	return n
}

func sovFarming(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFarming(x uint64) (n int) {
	return sovFarming(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrivatePlanCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrivatePlanCreationFee = append(m.PrivatePlanCreationFee, types.Coin{})
			if err := m.PrivatePlanCreationFee[len(m.PrivatePlanCreationFee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextEpochDays", wireType)
			}
			m.NextEpochDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextEpochDays |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FarmingFeeCollector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FarmingFeeCollector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFarming(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFarming
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BasePlan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BasePlan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BasePlan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= PlanType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FarmingPoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FarmingPoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TerminationAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TerminationAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingCoinWeights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingCoinWeights = append(m.StakingCoinWeights, types.DecCoin{})
			if err := m.StakingCoinWeights[len(m.StakingCoinWeights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Terminated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Terminated = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastDistributionTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastDistributionTime == nil {
				m.LastDistributionTime = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.LastDistributionTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributedCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistributedCoins = append(m.DistributedCoins, types.Coin{})
			if err := m.DistributedCoins[len(m.DistributedCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFarming(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFarming
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FixedAmountPlan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FixedAmountPlan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FixedAmountPlan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BasePlan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BasePlan == nil {
				m.BasePlan = &BasePlan{}
			}
			if err := m.BasePlan.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochAmount = append(m.EpochAmount, types.Coin{})
			if err := m.EpochAmount[len(m.EpochAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFarming(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFarming
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RatioPlan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RatioPlan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RatioPlan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BasePlan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BasePlan == nil {
				m.BasePlan = &BasePlan{}
			}
			if err := m.BasePlan.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EpochRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFarming(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFarming
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Staking) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Staking: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Staking: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartingEpoch", wireType)
			}
			m.StartingEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartingEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFarming(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFarming
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueuedStaking) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueuedStaking: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueuedStaking: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFarming(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFarming
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TotalStakings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TotalStakings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TotalStakings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFarming(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFarming
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HistoricalRewards) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HistoricalRewards: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HistoricalRewards: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CumulativeUnitRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CumulativeUnitRewards = append(m.CumulativeUnitRewards, types.DecCoin{})
			if err := m.CumulativeUnitRewards[len(m.CumulativeUnitRewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFarming(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFarming
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFarming(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFarming
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFarming
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFarming
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFarming        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFarming          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFarming = fmt.Errorf("proto: unexpected end of group")
)
