// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/farming/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	types1 "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the farming module's genesis state.
type GenesisState struct {
	// params defines all the parameters for the farming module
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// plan_records defines the plan records used for genesis state
	PlanRecords              []PlanRecord              `protobuf:"bytes,2,rep,name=plan_records,json=planRecords,proto3" json:"plan_records" yaml:"plan_records"`
	StakingRecords           []StakingRecord           `protobuf:"bytes,3,rep,name=staking_records,json=stakingRecords,proto3" json:"staking_records" yaml:"staking_records"`
	QueuedStakingRecords     []QueuedStakingRecord     `protobuf:"bytes,4,rep,name=queued_staking_records,json=queuedStakingRecords,proto3" json:"queued_staking_records" yaml:"queued_staking_records"`
	HistoricalRewardsRecords []HistoricalRewardsRecord `protobuf:"bytes,5,rep,name=historical_rewards_records,json=historicalRewardsRecords,proto3" json:"historical_rewards_records" yaml:"historical_rewards_records"`
	CurrentEpochRecords      []CurrentEpochRecord      `protobuf:"bytes,6,rep,name=current_epoch_records,json=currentEpochRecords,proto3" json:"current_epoch_records" yaml:"current_epoch_records"`
	// staking_reserve_coins specifies balance of the staking reserve pool staked in the plans
	// this param is needed for import/export validation
	StakingReserveCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,7,rep,name=staking_reserve_coins,json=stakingReserveCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"staking_reserve_coins" yaml:"staking_reserve_coins"`
	// reward_pool_coins specifies balance of the reward pool to be distributed in the plans
	// this param is needed for import/export validation
	RewardPoolCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,8,rep,name=reward_pool_coins,json=rewardPoolCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"reward_pool_coins" yaml:"reward_pool_coins"`
	// global_last_epoch_time specifies the last executed epoch time of the plans
	GlobalLastEpochTime time.Time `protobuf:"bytes,9,opt,name=global_last_epoch_time,json=globalLastEpochTime,proto3,stdtime" json:"global_last_epoch_time" yaml:"global_last_epoch_time"`
	// current_epoch_days specifies the epoch used when allocating farming rewards in end blocker
	CurrentEpochDays uint32 `protobuf:"varint,10,opt,name=current_epoch_days,json=currentEpochDays,proto3" json:"current_epoch_days,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c67612b66bcd2967, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

// PlanRecord is used for import/export via genesis json.
type PlanRecord struct {
	// plan specifies the plan interface; it can be FixedAmountPlan or RatioPlan
	Plan types1.Any `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan"`
	// farming_pool_coins specifies balance of the farming pool for the plan
	// this param is needed for import/export validation
	FarmingPoolCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=farming_pool_coins,json=farmingPoolCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"farming_pool_coins" yaml:"farming_pool_coins"`
	// staking_reserve_coins specifies balance of the staking reserve pool staked
	// in the plan this param is needed for import/export validation
	StakingReserveCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=staking_reserve_coins,json=stakingReserveCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"staking_reserve_coins" yaml:"staking_reserve_coins"`
}

func (m *PlanRecord) Reset()         { *m = PlanRecord{} }
func (m *PlanRecord) String() string { return proto.CompactTextString(m) }
func (*PlanRecord) ProtoMessage()    {}
func (*PlanRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c67612b66bcd2967, []int{1}
}
func (m *PlanRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PlanRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PlanRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PlanRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanRecord.Merge(m, src)
}
func (m *PlanRecord) XXX_Size() int {
	return m.Size()
}
func (m *PlanRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PlanRecord proto.InternalMessageInfo

type StakingRecord struct {
	StakingCoinDenom string  `protobuf:"bytes,1,opt,name=staking_coin_denom,json=stakingCoinDenom,proto3" json:"staking_coin_denom,omitempty" yaml:"staking_coin_denom"`
	Farmer           string  `protobuf:"bytes,2,opt,name=farmer,proto3" json:"farmer,omitempty"`
	Staking          Staking `protobuf:"bytes,3,opt,name=staking,proto3" json:"staking"`
}

func (m *StakingRecord) Reset()         { *m = StakingRecord{} }
func (m *StakingRecord) String() string { return proto.CompactTextString(m) }
func (*StakingRecord) ProtoMessage()    {}
func (*StakingRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c67612b66bcd2967, []int{2}
}
func (m *StakingRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StakingRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StakingRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StakingRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakingRecord.Merge(m, src)
}
func (m *StakingRecord) XXX_Size() int {
	return m.Size()
}
func (m *StakingRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_StakingRecord.DiscardUnknown(m)
}

var xxx_messageInfo_StakingRecord proto.InternalMessageInfo

type QueuedStakingRecord struct {
	StakingCoinDenom string        `protobuf:"bytes,1,opt,name=staking_coin_denom,json=stakingCoinDenom,proto3" json:"staking_coin_denom,omitempty" yaml:"staking_coin_denom"`
	Farmer           string        `protobuf:"bytes,2,opt,name=farmer,proto3" json:"farmer,omitempty"`
	QueuedStaking    QueuedStaking `protobuf:"bytes,3,opt,name=queued_staking,json=queuedStaking,proto3" json:"queued_staking" yaml:"queued_staking"`
}

func (m *QueuedStakingRecord) Reset()         { *m = QueuedStakingRecord{} }
func (m *QueuedStakingRecord) String() string { return proto.CompactTextString(m) }
func (*QueuedStakingRecord) ProtoMessage()    {}
func (*QueuedStakingRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c67612b66bcd2967, []int{3}
}
func (m *QueuedStakingRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueuedStakingRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueuedStakingRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueuedStakingRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuedStakingRecord.Merge(m, src)
}
func (m *QueuedStakingRecord) XXX_Size() int {
	return m.Size()
}
func (m *QueuedStakingRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuedStakingRecord.DiscardUnknown(m)
}

var xxx_messageInfo_QueuedStakingRecord proto.InternalMessageInfo

type HistoricalRewardsRecord struct {
	StakingCoinDenom  string            `protobuf:"bytes,1,opt,name=staking_coin_denom,json=stakingCoinDenom,proto3" json:"staking_coin_denom,omitempty" yaml:"staking_coin_denom"`
	Epoch             uint64            `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	HistoricalRewards HistoricalRewards `protobuf:"bytes,3,opt,name=historical_rewards,json=historicalRewards,proto3" json:"historical_rewards" yaml:"historical_rewards"`
}

func (m *HistoricalRewardsRecord) Reset()         { *m = HistoricalRewardsRecord{} }
func (m *HistoricalRewardsRecord) String() string { return proto.CompactTextString(m) }
func (*HistoricalRewardsRecord) ProtoMessage()    {}
func (*HistoricalRewardsRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c67612b66bcd2967, []int{4}
}
func (m *HistoricalRewardsRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HistoricalRewardsRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HistoricalRewardsRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HistoricalRewardsRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoricalRewardsRecord.Merge(m, src)
}
func (m *HistoricalRewardsRecord) XXX_Size() int {
	return m.Size()
}
func (m *HistoricalRewardsRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoricalRewardsRecord.DiscardUnknown(m)
}

var xxx_messageInfo_HistoricalRewardsRecord proto.InternalMessageInfo

type CurrentEpochRecord struct {
	StakingCoinDenom string `protobuf:"bytes,1,opt,name=staking_coin_denom,json=stakingCoinDenom,proto3" json:"staking_coin_denom,omitempty" yaml:"staking_coin_denom"`
	CurrentEpoch     uint64 `protobuf:"varint,2,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty" yaml:"current_epoch"`
}

func (m *CurrentEpochRecord) Reset()         { *m = CurrentEpochRecord{} }
func (m *CurrentEpochRecord) String() string { return proto.CompactTextString(m) }
func (*CurrentEpochRecord) ProtoMessage()    {}
func (*CurrentEpochRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c67612b66bcd2967, []int{5}
}
func (m *CurrentEpochRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CurrentEpochRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CurrentEpochRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CurrentEpochRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentEpochRecord.Merge(m, src)
}
func (m *CurrentEpochRecord) XXX_Size() int {
	return m.Size()
}
func (m *CurrentEpochRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentEpochRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentEpochRecord proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenesisState)(nil), "cosmos.farming.v1beta1.GenesisState")
	proto.RegisterType((*PlanRecord)(nil), "cosmos.farming.v1beta1.PlanRecord")
	proto.RegisterType((*StakingRecord)(nil), "cosmos.farming.v1beta1.StakingRecord")
	proto.RegisterType((*QueuedStakingRecord)(nil), "cosmos.farming.v1beta1.QueuedStakingRecord")
	proto.RegisterType((*HistoricalRewardsRecord)(nil), "cosmos.farming.v1beta1.HistoricalRewardsRecord")
	proto.RegisterType((*CurrentEpochRecord)(nil), "cosmos.farming.v1beta1.CurrentEpochRecord")
}

func init() {
	proto.RegisterFile("tendermint/farming/v1beta1/genesis.proto", fileDescriptor_c67612b66bcd2967)
}

var fileDescriptor_c67612b66bcd2967 = []byte{
	// 942 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcf, 0x6f, 0xdc, 0x44,
	0x14, 0xde, 0xc9, 0x26, 0x69, 0x33, 0xc9, 0xb6, 0xe9, 0xec, 0x66, 0x71, 0x02, 0xb1, 0x53, 0x8b,
	0x48, 0x5b, 0x20, 0xb6, 0x5a, 0x0e, 0x48, 0x15, 0x08, 0x61, 0x8a, 0x00, 0xb5, 0x48, 0x61, 0xca,
	0x89, 0x8b, 0x35, 0xbb, 0x3b, 0x75, 0xac, 0x78, 0x3d, 0x5b, 0x8f, 0xb7, 0xb0, 0x70, 0x84, 0x43,
	0xc5, 0xa9, 0x12, 0x12, 0xe2, 0x46, 0x8f, 0xa8, 0x67, 0x2e, 0x9c, 0xb8, 0x56, 0x9c, 0x7a, 0xe4,
	0x94, 0xa2, 0xcd, 0x85, 0x2b, 0xfd, 0x0b, 0xd0, 0xfc, 0x58, 0xaf, 0x37, 0xb6, 0x49, 0x2b, 0x45,
	0x88, 0xd3, 0xda, 0x9e, 0xf7, 0xbe, 0xef, 0x7b, 0xef, 0xcd, 0x7b, 0x6f, 0x61, 0x27, 0xa5, 0x71,
	0x9f, 0x26, 0x83, 0x30, 0x4e, 0xdd, 0x3b, 0x44, 0xfc, 0x06, 0xee, 0xbd, 0xab, 0x5d, 0x9a, 0x92,
	0xab, 0x6e, 0x40, 0x63, 0xca, 0x43, 0xee, 0x0c, 0x13, 0x96, 0x32, 0xd4, 0xee, 0x31, 0x3e, 0x60,
	0xdc, 0xd1, 0x56, 0x8e, 0xb6, 0xda, 0xda, 0x0c, 0x18, 0x0b, 0x22, 0xea, 0x4a, 0xab, 0xee, 0xe8,
	0x8e, 0x4b, 0xe2, 0xb1, 0x72, 0xd9, 0x6a, 0x05, 0x2c, 0x60, 0xf2, 0xd1, 0x15, 0x4f, 0xfa, 0xeb,
	0xa6, 0x02, 0xf2, 0xd5, 0x81, 0x46, 0x55, 0x47, 0xa6, 0x7a, 0x73, 0xbb, 0x84, 0xd3, 0x4c, 0x46,
	0x8f, 0x85, 0xb1, 0x3e, 0xff, 0x37, 0xb5, 0x53, 0x5d, 0xca, 0xd2, 0x3a, 0xa9, 0x2a, 0x0d, 0x07,
	0x94, 0xa7, 0x64, 0x30, 0x54, 0x06, 0xf6, 0xaf, 0x2b, 0x70, 0xed, 0x43, 0x15, 0xe0, 0xed, 0x94,
	0xa4, 0x14, 0xbd, 0x0d, 0x97, 0x87, 0x24, 0x21, 0x03, 0x6e, 0x80, 0x1d, 0xd0, 0x59, 0xbd, 0x66,
	0x3a, 0xe5, 0x01, 0x3b, 0xfb, 0xd2, 0xca, 0x5b, 0x7c, 0x7c, 0x64, 0xd5, 0xb0, 0xf6, 0x41, 0x5d,
	0xb8, 0x36, 0x8c, 0x48, 0xec, 0x27, 0xb4, 0xc7, 0x92, 0x3e, 0x37, 0x16, 0x76, 0xea, 0x9d, 0xd5,
	0x6b, 0x76, 0x25, 0x46, 0x44, 0x62, 0x2c, 0x4d, 0xbd, 0x97, 0x05, 0xce, 0xb3, 0x23, 0xab, 0x39,
	0x26, 0x83, 0xe8, 0xba, 0x9d, 0x47, 0xb1, 0xf1, 0xea, 0x30, 0x33, 0xe4, 0x28, 0x86, 0x17, 0x79,
	0x4a, 0x0e, 0xc3, 0x38, 0xc8, 0x68, 0xea, 0x92, 0x66, 0xb7, 0x8a, 0xe6, 0xb6, 0x32, 0xd7, 0x4c,
	0xa6, 0x66, 0x6a, 0x2b, 0xa6, 0x13, 0x58, 0x36, 0xbe, 0xc0, 0xf3, 0xe6, 0x1c, 0xdd, 0x07, 0xb0,
	0x7d, 0x77, 0x44, 0x47, 0xb4, 0xef, 0x9f, 0xe4, 0x5d, 0x94, 0xbc, 0xaf, 0x57, 0xf1, 0x7e, 0x2a,
	0xbd, 0xe6, 0xd9, 0x77, 0x35, 0xfb, 0xb6, 0x62, 0x2f, 0x07, 0xb6, 0x71, 0xeb, 0x6e, 0xd1, 0x97,
	0xa3, 0x1f, 0x01, 0xdc, 0x3a, 0x08, 0x79, 0xca, 0x92, 0xb0, 0x47, 0x22, 0x3f, 0xa1, 0x5f, 0x90,
	0xa4, 0xcf, 0x33, 0x39, 0x4b, 0x52, 0x8e, 0x5b, 0x25, 0xe7, 0xa3, 0xcc, 0x13, 0x2b, 0x47, 0x2d,
	0xe9, 0x8a, 0x96, 0x74, 0x59, 0x49, 0xaa, 0x26, 0xb0, 0xb1, 0x71, 0x50, 0x8e, 0xc1, 0xd1, 0xb7,
	0x00, 0x6e, 0xf4, 0x46, 0x49, 0x42, 0xe3, 0xd4, 0xa7, 0x43, 0xd6, 0x3b, 0xc8, 0x54, 0x2d, 0x4b,
	0x55, 0xaf, 0x55, 0xa9, 0x7a, 0x5f, 0x39, 0x7d, 0x20, 0x7c, 0xb4, 0xa0, 0x57, 0xb5, 0xa0, 0x57,
	0x94, 0xa0, 0x52, 0x58, 0x1b, 0x37, 0x7b, 0x05, 0x4f, 0x8e, 0x7e, 0x02, 0x70, 0x63, 0x96, 0x4c,
	0x4e, 0x93, 0x7b, 0xd4, 0x17, 0x9d, 0xc3, 0x8d, 0x73, 0x52, 0xc6, 0xe6, 0x54, 0x86, 0xe8, 0xad,
	0x99, 0x06, 0x16, 0xc6, 0xde, 0xfe, 0x3c, 0x6b, 0x29, 0x8a, 0xfd, 0xe8, 0xa9, 0xd5, 0x09, 0xc2,
	0xf4, 0x60, 0xd4, 0x75, 0x7a, 0x6c, 0xa0, 0xdb, 0x56, 0xff, 0xec, 0xf1, 0xfe, 0xa1, 0x9b, 0x8e,
	0x87, 0x94, 0x4b, 0x40, 0x8e, 0x9b, 0xd9, 0x4d, 0x92, 0x10, 0xf2, 0x23, 0xfa, 0x1e, 0xc0, 0x4b,
	0x2a, 0xaf, 0xfe, 0x90, 0xb1, 0x48, 0xab, 0x3b, 0x7f, 0x9a, 0xba, 0x5b, 0x5a, 0x9d, 0xa1, 0xd4,
	0x15, 0x10, 0x5e, 0x4c, 0xd9, 0x45, 0xe5, 0xbf, 0xcf, 0x58, 0xa4, 0x54, 0x7d, 0x05, 0xdb, 0x41,
	0xc4, 0xba, 0x24, 0xf2, 0x23, 0xc2, 0xa7, 0xa9, 0x16, 0xc3, 0xc2, 0x58, 0x91, 0x63, 0x60, 0xcb,
	0x51, 0x93, 0xc4, 0x99, 0x4e, 0x12, 0xe7, 0xb3, 0xe9, 0x24, 0xc9, 0xee, 0x8f, 0xbe, 0xd2, 0xe5,
	0x38, 0xf6, 0x83, 0xa7, 0x16, 0xc0, 0x4d, 0x75, 0x78, 0x8b, 0x70, 0x55, 0x36, 0x01, 0x82, 0xde,
	0x80, 0x68, 0xbe, 0xc4, 0x7d, 0x32, 0xe6, 0x06, 0xdc, 0x01, 0x9d, 0x06, 0x5e, 0xcf, 0x17, 0xf9,
	0x06, 0x19, 0xf3, 0xeb, 0xe7, 0xef, 0x3f, 0xb4, 0x6a, 0x7f, 0x3d, 0xb4, 0x6a, 0xf6, 0x77, 0x75,
	0x08, 0x67, 0x13, 0x04, 0xbd, 0x05, 0x17, 0xc5, 0x98, 0xd0, 0x73, 0xab, 0x55, 0x10, 0xfc, 0x5e,
	0x3c, 0xf6, 0x1a, 0x42, 0xea, 0xef, 0xbf, 0xec, 0x2d, 0x09, 0xbf, 0x8f, 0xb1, 0x74, 0x40, 0x3f,
	0x00, 0x88, 0xf4, 0xad, 0xcc, 0x97, 0x64, 0xe1, 0xb4, 0x92, 0x7c, 0xa2, 0xe3, 0xde, 0x54, 0x71,
	0x17, 0x21, 0x5e, 0xac, 0x26, 0xeb, 0x1a, 0x60, 0x56, 0x94, 0xea, 0xcb, 0x5c, 0xff, 0x7f, 0x5c,
	0xe6, 0x5c, 0x31, 0x7e, 0x03, 0xb0, 0x31, 0x37, 0xad, 0xd0, 0x4d, 0x88, 0xa6, 0xb4, 0x82, 0xce,
	0xef, 0xd3, 0x98, 0x0d, 0x64, 0x75, 0x56, 0xbc, 0xed, 0x59, 0xda, 0x8a, 0x36, 0x36, 0x5e, 0xd7,
	0x1f, 0x05, 0xc9, 0x0d, 0xf1, 0x09, 0xb5, 0xe1, 0xb2, 0x48, 0x0f, 0x4d, 0x8c, 0x05, 0x01, 0x80,
	0xf5, 0x1b, 0x7a, 0x17, 0x9e, 0xd3, 0xb6, 0x46, 0x5d, 0xd6, 0xdd, 0x3a, 0x65, 0x09, 0xe8, 0x85,
	0x35, 0xf5, 0xca, 0x45, 0xf0, 0x37, 0x80, 0xcd, 0x92, 0x89, 0xfd, 0xdf, 0xc4, 0x71, 0x08, 0x2f,
	0xcc, 0xaf, 0x02, 0x1d, 0xce, 0xee, 0x73, 0xed, 0x16, 0x6f, 0x5b, 0x97, 0x7b, 0xa3, 0x6c, 0xab,
	0xd8, 0xb8, 0x31, 0xb7, 0x4d, 0x72, 0x31, 0x7f, 0xb3, 0x00, 0x5f, 0xaa, 0x58, 0x0b, 0x67, 0x1b,
	0x77, 0x0b, 0x2e, 0xc9, 0xde, 0x96, 0x61, 0x2f, 0x62, 0xf5, 0x82, 0xbe, 0x86, 0xa8, 0xb8, 0x6d,
	0x74, 0xe4, 0x57, 0x9e, 0x7b, 0x8d, 0x79, 0x97, 0xe7, 0x1b, 0xb1, 0x08, 0x69, 0xe3, 0x4b, 0x85,
	0xc5, 0x95, 0xcb, 0xc2, 0x23, 0x00, 0x51, 0x71, 0x0d, 0x9d, 0x6d, 0x02, 0xde, 0x81, 0x8d, 0xb9,
	0x21, 0xa7, 0x12, 0xe1, 0x19, 0xcf, 0x8e, 0xac, 0x56, 0xc9, 0x9a, 0xb3, 0xf1, 0x5a, 0x7e, 0xf2,
	0xcd, 0xc4, 0x7a, 0x37, 0x7f, 0x9e, 0x98, 0xe0, 0xf1, 0xc4, 0x04, 0x4f, 0x26, 0x26, 0xf8, 0x73,
	0x62, 0x82, 0x07, 0xc7, 0x66, 0xed, 0xc9, 0xb1, 0x59, 0xfb, 0xe3, 0xd8, 0xac, 0x7d, 0xbe, 0x97,
	0xeb, 0xe7, 0x92, 0x7f, 0x89, 0x5f, 0x66, 0x4f, 0xb2, 0xb5, 0xbb, 0xcb, 0x72, 0x3a, 0xbe, 0xf9,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x54, 0x68, 0x3d, 0x00, 0x0b, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentEpochDays != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CurrentEpochDays))
		i--
		dAtA[i] = 0x50
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.GlobalLastEpochTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.GlobalLastEpochTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintGenesis(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x4a
	if len(m.RewardPoolCoins) > 0 {
		for iNdEx := len(m.RewardPoolCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardPoolCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.StakingReserveCoins) > 0 {
		for iNdEx := len(m.StakingReserveCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakingReserveCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.CurrentEpochRecords) > 0 {
		for iNdEx := len(m.CurrentEpochRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CurrentEpochRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.HistoricalRewardsRecords) > 0 {
		for iNdEx := len(m.HistoricalRewardsRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HistoricalRewardsRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.QueuedStakingRecords) > 0 {
		for iNdEx := len(m.QueuedStakingRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.QueuedStakingRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.StakingRecords) > 0 {
		for iNdEx := len(m.StakingRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakingRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PlanRecords) > 0 {
		for iNdEx := len(m.PlanRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PlanRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PlanRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlanRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PlanRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StakingReserveCoins) > 0 {
		for iNdEx := len(m.StakingReserveCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakingReserveCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.FarmingPoolCoins) > 0 {
		for iNdEx := len(m.FarmingPoolCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FarmingPoolCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Plan.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *StakingRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StakingRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StakingRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Staking.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Farmer) > 0 {
		i -= len(m.Farmer)
		copy(dAtA[i:], m.Farmer)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Farmer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.StakingCoinDenom) > 0 {
		i -= len(m.StakingCoinDenom)
		copy(dAtA[i:], m.StakingCoinDenom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.StakingCoinDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueuedStakingRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueuedStakingRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueuedStakingRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.QueuedStaking.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Farmer) > 0 {
		i -= len(m.Farmer)
		copy(dAtA[i:], m.Farmer)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Farmer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.StakingCoinDenom) > 0 {
		i -= len(m.StakingCoinDenom)
		copy(dAtA[i:], m.StakingCoinDenom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.StakingCoinDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HistoricalRewardsRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HistoricalRewardsRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HistoricalRewardsRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.HistoricalRewards.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Epoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.StakingCoinDenom) > 0 {
		i -= len(m.StakingCoinDenom)
		copy(dAtA[i:], m.StakingCoinDenom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.StakingCoinDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CurrentEpochRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CurrentEpochRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CurrentEpochRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CurrentEpoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.StakingCoinDenom) > 0 {
		i -= len(m.StakingCoinDenom)
		copy(dAtA[i:], m.StakingCoinDenom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.StakingCoinDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.PlanRecords) > 0 {
		for _, e := range m.PlanRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.StakingRecords) > 0 {
		for _, e := range m.StakingRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.QueuedStakingRecords) > 0 {
		for _, e := range m.QueuedStakingRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HistoricalRewardsRecords) > 0 {
		for _, e := range m.HistoricalRewardsRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CurrentEpochRecords) > 0 {
		for _, e := range m.CurrentEpochRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.StakingReserveCoins) > 0 {
		for _, e := range m.StakingReserveCoins {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RewardPoolCoins) > 0 {
		for _, e := range m.RewardPoolCoins {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.GlobalLastEpochTime)
	n += 1 + l + sovGenesis(uint64(l))
	if m.CurrentEpochDays != 0 {
		n += 1 + sovGenesis(uint64(m.CurrentEpochDays))
	}
	return n
}

func (m *PlanRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Plan.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.FarmingPoolCoins) > 0 {
		for _, e := range m.FarmingPoolCoins {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.StakingReserveCoins) > 0 {
		for _, e := range m.StakingReserveCoins {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *StakingRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StakingCoinDenom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Farmer)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Staking.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *QueuedStakingRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StakingCoinDenom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Farmer)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.QueuedStaking.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *HistoricalRewardsRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StakingCoinDenom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovGenesis(uint64(m.Epoch))
	}
	l = m.HistoricalRewards.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *CurrentEpochRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StakingCoinDenom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.CurrentEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.CurrentEpoch))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlanRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlanRecords = append(m.PlanRecords, PlanRecord{})
			if err := m.PlanRecords[len(m.PlanRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingRecords = append(m.StakingRecords, StakingRecord{})
			if err := m.StakingRecords[len(m.StakingRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueuedStakingRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueuedStakingRecords = append(m.QueuedStakingRecords, QueuedStakingRecord{})
			if err := m.QueuedStakingRecords[len(m.QueuedStakingRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HistoricalRewardsRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HistoricalRewardsRecords = append(m.HistoricalRewardsRecords, HistoricalRewardsRecord{})
			if err := m.HistoricalRewardsRecords[len(m.HistoricalRewardsRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpochRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentEpochRecords = append(m.CurrentEpochRecords, CurrentEpochRecord{})
			if err := m.CurrentEpochRecords[len(m.CurrentEpochRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingReserveCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingReserveCoins = append(m.StakingReserveCoins, types.Coin{})
			if err := m.StakingReserveCoins[len(m.StakingReserveCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPoolCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardPoolCoins = append(m.RewardPoolCoins, types.Coin{})
			if err := m.RewardPoolCoins[len(m.RewardPoolCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalLastEpochTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.GlobalLastEpochTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpochDays", wireType)
			}
			m.CurrentEpochDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpochDays |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlanRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlanRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlanRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Plan.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FarmingPoolCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FarmingPoolCoins = append(m.FarmingPoolCoins, types.Coin{})
			if err := m.FarmingPoolCoins[len(m.FarmingPoolCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingReserveCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingReserveCoins = append(m.StakingReserveCoins, types.Coin{})
			if err := m.StakingReserveCoins[len(m.StakingReserveCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StakingRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StakingRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StakingRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Farmer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Farmer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staking", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Staking.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueuedStakingRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueuedStakingRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueuedStakingRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Farmer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Farmer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueuedStaking", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.QueuedStaking.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HistoricalRewardsRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HistoricalRewardsRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HistoricalRewardsRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HistoricalRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.HistoricalRewards.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CurrentEpochRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CurrentEpochRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CurrentEpochRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpoch", wireType)
			}
			m.CurrentEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
